config/routes.rb
Trial::Application.routes.draw do
  
  root to: 'pages#show', page_path: 'index'

  
  get '(*page_path)/edit', to: 'pages#edit', as: :page, page_path: 'index' #по дефолту index
  get '(*page_path)/add', to: 'pages#add'
  get '*page_path', to: 'pages#show'

  put ':id/edit', to: 'pages#update'
  post '/add', to: 'pages#create'
  

end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :pagename, :pagetitle, :parent_id

  has_many :subpages, class_name: "Page", foreign_key: 'parent_id'
  belongs_to :parent, class_name: "Page", foreign_key: 'parent_id'
  #валидация урла.
  validates :pagename, presence: {:on => :create},  uniqueness: {:on => :create}, format: { :with => /\A[[[:alnum:]]_\/]+\z/}
  validates_presence_of  :pagetitle

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  #получаем страницу по ее адресу.
  before_filter :get_page_from_address, only: [:show, :add, :edit]

  # *page GET
  def show
    # если страница не найдена, отдаем соответствующй текст и статус.
      unless @page
        render file: 'public/404.html', status: 404 #'page not found', status: 404 #params.inspect
      else
    end
  end

  # *page/edit GET
  def edit
  
  end

  # /update PUT
  def update
    #обновляем ресурс
    @page = Page.find(params[:id])
    @page.update_attributes(params[:page])
    if @page.errors.empty?
      #если страница главная, отправляем в корень, в противном случае на отредактированную страницу
      unless @page.pagename == 'index'
        redirect_to "/#{@page.pagename}"
      else
        redirect_to "/"
      end
    else
      render text: "edit"
    end
  end

  # добавлеие страницы
  # *page/add GET
  def add
  end

  # *page/add POST
  def create
  # если создаем страницу не в корне, то необходимо в pagename добавить адрес родительской страницы.
    if (params[:page][:parent_id])
      parent_path = Page.where("id = ?",params[:page][:parent_id]).pluck(:pagename).first
      params[:page][:pagename] = "#{parent_path}/#{params[:page][:pagename]}"
    end
    #создаем новю страницу
    @page = Page.create(params[:page])
    if @page.errors.empty?
      #редиректим на вновь созданную страницу
      redirect_to "/#{@page.pagename}"
     else
      #если есть ошибки, то возвращаемся к форме редактировния
      redirect_to request.referer #"/#{parms}"
    end
  end

  private
  # поиск страниц по адресу
  def get_page_from_address
    @page = Page.find_by_pagename(params[:page_path])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def replace_tags(s)
    # если необходимо менять не отдельные слова разделенные пробелом ,а например строку, подобную этой:
    # text_**without**_spaces, то необходимо убрать \s в конце и в начале регулярных выражений.

    #преобразовывем ссылки 
    s.gsub! /\s\(\((.*?)\s\[(.*?)\]\)\)\s/,  '<a href="'+request.protocol+request.host_with_port+'/\1">\2</a>'
    #преобразовываем **x** в <b>x</b>
    s.gsub! /\s\*\*(.*?)\*\*\s/, '<b>\1</b>'
    #преобразовываем \\x\\ в <i>x</i>
    s.gsub! /\s\\\\(.*?)\\\\\s/, '<i>\1</i>'
    s.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<p>Название страницы <br><%= f.text_field :pagetitle %></p>
<p>Текст страницы <br><%= f.text_area :content %></p>

app/views/pages/add.html.erb
<h1>Добаление страницы </h1>
<% #указываем :url для того, что бы роут вел на эту же страницу. %>
<%= form_for(Page.new, :url => "/add") do |f| %>
  <%= f.hidden_field(:parent_id, :value => @page.id) if @page %>
  <p>Имя страницы <br><%= f.text_field :pagename %></p>
	<%= render partial: "form", locals: {f: f} %>
	<p><%= f.submit "добавить" %></p>
<% end %>

app/views/pages/edit.html.erb
<h1>Редактирование страницы </h1>
<%= form_for @page do |f| %>
	<%= render partial: "form", locals: {f: f} %>
	<p><%= f.submit "сохранить" %></p>
<% end %>

app/views/pages/index.html.erb
pages index

<%= link_to 'Новая страница', :action => 'new' %><br />
<%= link_to 'Новая страница', new_page_path %><br />
<%= link_to 'Новая страница', new_page_url %><br />

app/views/pages/show.erb
pages index

<%= link_to 'Новая страница', :action => 'new' %><br />
<%= link_to 'Новая страница', new_page_path %><br />
<%= link_to 'Новая страница', new_page_url %><br />

app/views/pages/show.html.erb
<h1><%= @page.pagetitle %></h1>
<p><%= replace_tags(@page.content) %></p>

<br>

<ul>
	<% for page in @page.subpages  %>
		<li><a href="/<%=page.pagename%>"><%= page.pagetitle %></a></li>
	<% end %>
</ul>

